### ISSUE TITLE
Bug to be fix, interview list not updated when application is updated

### ISSUE THREAD

**Issue by eesung00** [AY2223S1-CS2103-F14-3/tp#105]
For example, after running `edit 1 c/Lala` interview list will still have interview with Google.

Before
![image](https://user-images.githubusercontent.com/90175879/196991898-5b60b78c-d7ca-4703-bdfe-2c7b17fc2b34.png)
After
![image](https://user-images.githubusercontent.com/90175879/196992244-64720059-4304-460e-82f5-4da00b9a3253.png)

**Comment by nmtuan2001** [comment]
Same bug if you run `clear`. I can quickly fix this one.
