### ISSUE TITLE
Wrong error message for AddCommand

### ISSUE THREAD

**Issue by nmtuan2001** [AY2223S1-CS2103-F14-3/tp#106]
<img width="545" alt="image" src="https://user-images.githubusercontent.com/64367560/196994804-a474279e-24ef-4771-9213-09b9adcee65b.png">

This command is copied from the help message.

**Comment by nmtuan2001** [comment]
<img width="539" alt="image" src="https://user-images.githubusercontent.com/64367560/196995730-7f66004a-bb92-4bfc-bdd5-2d33abfb26e8.png">

Also, there seems to be a problem with tags.

**Comment by teekaytai** [comment]
I think the tags are fine, it's just that they don't allow spaces
