### ISSUE TITLE
Find Command Possible Documentation bug flagged by someone

### ISSUE THREAD

**Issue by eesung00** [AY2223S1-CS2103-F14-3/tp#212]
After the find command is executed, the interview list will not update. Is this stated somewhere in UG? Perhaps can summarise when will the interview list in sync with the application list and when it will not be in sync UG

![image](https://user-images.githubusercontent.com/90175879/200132691-39ae7d97-4538-4c41-92b7-b83be214b458.png)

**Comment by teekaytai** [comment]
Yup this is intended, but you're right we should mention this in the UG somewhere.
