### ISSUE TITLE
Add Interview and its relevant fields 

### ISSUE THREAD

**Issue by jhchee18** [AY2223S1-CS2103-F14-3/tp#74]
To include `Interview` in `Application`

The tentative `Application` class will then look like below:

> - `Application` contains:
>   - `Company`
>   - `Contact`
>   - ...
>   - `Interview` contains:
>     - `Round`
>     - `InterviewDate`
>     - `InterviewTime`
>     - `Location`

One of the subtasks for #44 and #49

**Comment by nmtuan2001** [comment]
<img width="535" alt="image" src="https://user-images.githubusercontent.com/64367560/196943479-fc042a55-9f90-40ff-bf0e-e0fb0e9b4ab2.png">
Hello sorry for reopening this issue. I was testing Interview with undo/redo commands when I noticed that the message shown here doesn't break into multiple lines so it looks quite crammed. 

But the main issue is that when there is a time clash, it still shows this same error, which can be misleading. And I couldn't change an existing interview (change location/round) and keep the same time (since there is a time clash). Is there a possible fix for this?

**Comment by eesung00** [comment]
> <img alt="image" width="535" src="https://user-images.githubusercontent.com/64367560/196943479-fc042a55-9f90-40ff-bf0e-e0fb0e9b4ab2.png">
> 
> Hello sorry for reopening this issue. I was testing Interview with undo/redo commands when I noticed that the message shown here doesn't break into multiple lines so it looks quite crammed.
> But the main issue is that when there is a time clash, it still shows this same error, which can be misleading. And I couldn't change an existing interview (change location/round) and keep the same time (since there is a time clash). Is there a possible fix for this?

Yup, if interview to be edited has the same information with the edited one, `InvalidInterviewException` will somewhat be thrown somewhere. Should output message about duplicate similar to editing the application. Have any idea on where is the problem? 😅 @jhchee18 I tried to find but dunno where

**Comment by jhchee18** [comment]
> <img alt="image" width="535" src="https://user-images.githubusercontent.com/64367560/196943479-fc042a55-9f90-40ff-bf0e-e0fb0e9b4ab2.png">
> 
> Hello sorry for reopening this issue. I was testing Interview with undo/redo commands when I noticed that the message shown here doesn't break into multiple lines so it looks quite crammed.
> But the main issue is that when there is a time clash, it still shows this same error, which can be misleading. And I couldn't change an existing interview (change location/round) and keep the same time (since there is a time clash). Is there a possible fix for this?

Main issue was fixed in PR #104 . The long message display can be fixed in the next version.

**Comment by jhchee18** [comment]
> > <img alt="image" width="535" src="https://user-images.githubusercontent.com/64367560/196943479-fc042a55-9f90-40ff-bf0e-e0fb0e9b4ab2.png">
> > Hello sorry for reopening this issue. I was testing Interview with undo/redo commands when I noticed that the message shown here doesn't break into multiple lines so it looks quite crammed.
> > But the main issue is that when there is a time clash, it still shows this same error, which can be misleading. And I couldn't change an existing interview (change location/round) and keep the same time (since there is a time clash). Is there a possible fix for this?
> 
> Yup, if interview to be edited has the same information with the edited one, `InvalidInterviewException` will somewhat be thrown somewhere. Should output message about duplicate similar to editing the application. Have any idea on where is the problem? 😅 @jhchee18 I tried to find but dunno where

Uhmm.. sorry I can't recreate the error, can you elaborate more?

**Comment by eesung00** [comment]
> > > <img alt="image" width="535" src="https://user-images.githubusercontent.com/64367560/196943479-fc042a55-9f90-40ff-bf0e-e0fb0e9b4ab2.png">
> > > Hello sorry for reopening this issue. I was testing Interview with undo/redo commands when I noticed that the message shown here doesn't break into multiple lines so it looks quite crammed.
> > > But the main issue is that when there is a time clash, it still shows this same error, which can be misleading. And I couldn't change an existing interview (change location/round) and keep the same time (since there is a time clash). Is there a possible fix for this?
> > 
> > 
> > Yup, if interview to be edited has the same information with the edited one, `InvalidInterviewException` will somewhat be thrown somewhere. Should output message about duplicate similar to editing the application. Have any idea on where is the problem? 😅 @jhchee18 I tried to find but dunno where
> 
> Uhmm.. sorry I can't recreate the error, can you elaborate more?

Oh sorry I think I made mistake thought it was a bug, can close this issue
